# Generated by Django 5.1.3 on 2024-11-14 06:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100)),
                ('website', models.URLField(blank=True)),
                ('bio', models.TextField(blank=True)),
                ('company_logo', models.ImageField(blank=True, null=True, upload_to='company_logos/')),
                ('location', models.CharField(help_text='City, Country', max_length=100)),
                ('industry', models.CharField(help_text='e.g., Information Technology, Healthcare', max_length=100)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('contact_phone', models.CharField(blank=True, max_length=15)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=100)),
                ('salary', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('employment_type', models.CharField(choices=[('full-time', 'Full-Time'), ('part-time', 'Part-Time'), ('contract', 'Contract'), ('internship', 'Internship'), ('temporary', 'Temporary')], max_length=20)),
                ('posted_date', models.DateField(auto_now_add=True)),
                ('deadline', models.DateField()),
                ('experience_required', models.IntegerField(blank=True, help_text='Number of years of experience required', null=True)),
                ('qualifications', models.TextField(blank=True, help_text='Qualifications or education level required')),
                ('responsibilities', models.TextField(blank=True, help_text='Key responsibilities for the role')),
                ('benefits', models.TextField(blank=True, help_text='Benefits and perks offered by the company')),
                ('skills_required', models.TextField(blank=True, help_text='List skills required for this job, separated by commas.')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='jobs.employer')),
            ],
        ),
        migrations.CreateModel(
            name='JobSeeker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('resume', models.FileField(upload_to='resumes/')),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profile_pictures/')),
                ('skills', models.TextField(help_text='List skills separated by commas.')),
                ('experience', models.IntegerField(help_text='Number of years of experience')),
                ('education', models.CharField(max_length=100)),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('location', models.CharField(help_text='City, Country', max_length=100)),
                ('linkedin_url', models.URLField(blank=True, null=True)),
                ('portfolio_url', models.URLField(blank=True, null=True)),
                ('summary', models.TextField(blank=True, help_text='A brief professional summary or bio.')),
                ('certifications', models.TextField(blank=True, help_text='Certifications separated by commas.')),
                ('languages', models.CharField(blank=True, help_text='Languages spoken, separated by commas.', max_length=200)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applied_date', models.DateField(auto_now_add=True)),
                ('status', models.CharField(choices=[('applied', 'Applied'), ('reviewed', 'Reviewed'), ('interviewed', 'Interviewed'), ('offered', 'Offered'), ('hired', 'Hired'), ('rejected', 'Rejected')], default='applied', max_length=20)),
                ('resume', models.FileField(blank=True, help_text='Uploaded resume for this specific application.', upload_to='application_resumes/')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='jobs.job')),
                ('job_seeker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='jobs.jobseeker')),
            ],
        ),
    ]
