# Generated by Django 5.1.4 on 2025-03-15 07:16

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('dob', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10)),
                ('experience', models.IntegerField(default=0)),
                ('skills', models.CharField(max_length=100)),
                ('job_title', models.CharField(blank=True, max_length=100)),
                ('department', models.CharField(blank=True, max_length=100)),
                ('phone_number', models.CharField(blank=True, max_length=15)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='employee_pictures/')),
                ('bio', models.TextField(blank=True, null=True)),
                ('company', models.CharField(max_length=100)),
                ('company_logo', models.ImageField(blank=True, null=True, upload_to='company_logos/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=100)),
                ('industry', models.CharField(choices=[('Information Technology', 'Information Technology'), ('Healthcare', 'Healthcare'), ('Finance', 'Finance')], default='Finance', max_length=30)),
                ('min_salary', models.DecimalField(blank=True, decimal_places=2, help_text='Minimum salary for this job (optional).', max_digits=10, null=True)),
                ('max_salary', models.DecimalField(blank=True, decimal_places=2, help_text='Maximum salary for this job (optional).', max_digits=10, null=True)),
                ('min_experience', models.PositiveIntegerField(default=0, help_text='Minimum years of experience required for this job.')),
                ('max_experience', models.PositiveIntegerField(blank=True, help_text='Maximum years of experience required for this job (optional).', null=True)),
                ('vacancies', models.PositiveIntegerField(default=1, help_text='Number of openings available for this job.')),
                ('job_type', models.CharField(choices=[('Full-time', 'Full-time'), ('Part-time', 'Part-time'), ('Contract', 'Contract')], default='Full-time', max_length=20)),
                ('job_mode', models.CharField(choices=[('Remote', 'Remote'), ('Work from Office', 'Work from Office'), ('Hybrid', 'Hybrid')], default='Work from Office', max_length=20)),
                ('deadline', models.DateField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('closed', 'Closed')], default='active', help_text='Indicates whether the job is active or closed.', max_length=10)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.employer')),
            ],
        ),
        migrations.CreateModel(
            name='JobSeeker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('resume', models.FileField(upload_to='resumes/')),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profile_pictures/')),
                ('skills', models.TextField(help_text='List skills separated by commas.')),
                ('experience', models.CharField(blank=True, max_length=500, null=True)),
                ('education', models.CharField(max_length=100)),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('location', models.CharField(help_text='City, Country', max_length=100)),
                ('linkedin_url', models.URLField(blank=True, null=True)),
                ('portfolio_url', models.URLField(blank=True, null=True)),
                ('summary', models.TextField(blank=True, help_text='A brief professional summary or bio.')),
                ('certifications', models.TextField(blank=True, help_text='Certifications separated by commas.')),
                ('languages', models.CharField(blank=True, help_text='Languages spoken, separated by commas.', max_length=200)),
                ('is_premium', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applied_date', models.DateField(auto_now_add=True)),
                ('status', models.CharField(choices=[('applied', 'Applied'), ('reviewed', 'Reviewed'), ('interview', 'Interview'), ('hire', 'Hire'), ('reject', 'Reject')], default='applied', help_text='Current status of the application', max_length=20)),
                ('resume', models.FileField(blank=True, help_text='Uploaded resume for this specific application. Leave blank to use the default resume.', null=True, upload_to='application_resumes/')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='jobs.job')),
                ('job_seeker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='jobs.jobseeker')),
            ],
            options={
                'verbose_name': 'Application',
                'verbose_name_plural': 'Applications',
                'ordering': ['-applied_date'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='jobs.application')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan', models.CharField(max_length=50)),
                ('subscription_id', models.CharField(blank=True, max_length=100, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
