# Generated by Django 5.1.3 on 2024-11-14 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobseeker',
            name='experience',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
