# Generated by Django 5.1.3 on 2024-11-24 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_job_status_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='job_mode',
            field=models.CharField(choices=[('Remote', 'Remote'), ('Work from Office', 'Work from Office'), ('Hybrid', 'Hybrid')], default='Work from Office', max_length=20),
        ),
    ]
