# Generated by Django 5.1.3 on 2024-11-24 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0007_job_job_mode'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='experience_level',
            new_name='min_experience',
        ),
        migrations.RemoveField(
            model_name='job',
            name='salary',
        ),
        migrations.AddField(
            model_name='job',
            name='max_experience',
            field=models.PositiveIntegerField(blank=True, help_text='Maximum years of experience required for this job (optional).', null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='max_salary',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Maximum salary for this job (optional).', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='min_salary',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Minimum salary for this job (optional).', max_digits=10, null=True),
        ),
    ]
