# Generated by Django 5.1.3 on 2024-11-27 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0010_job_vacancies_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobseeker',
            name='is_premium',
            field=models.BooleanField(default=False),
        ),
    ]
